# Required packages installation

- name:           Activate Jessie-backports
  apt_repository: repo="deb http://httpredir.debian.org/debian jessie-backports main" mode=644 state=present
  register:       backports
  become:         yes

- name:   Update apt cache
  apt:    update_cache=yes
  when:   backports.changed
  become: yes

- name: Install new packages
  apt:  name={{ item }}
  with_items: [ xvfb, build-essential ]
  become: yes

- name: Install Java 8 using jessie-backports
  apt:  name={{ item }} default_release=jessie-backports
  with_items: [ openjdk-8-jre, openjdk-8-jdk ]
  become: yes

# Eclipe installation

- name: Check if Eclipse has already been installed in a previous provisioning
  stat: path=/opt/eclipse
  register: eclipse_installed

- name: Check if Eclipse has already been downloaded in a previous provisioning
  stat: path=/tmp/eclipse.tar.gz
  when: eclipse_installed.stat.isdir | default(False) == False
  register: eclipse_downloaded

- name: Download Eclipse
  get_url:
    url:  http://mirrors.nic.cz/eclipse/technology/epp/downloads/release/neon/1a/eclipse-java-neon-1a-linux-gtk-x86_64.tar.gz
    dest: /tmp/eclipse.tar.gz
  when: (eclipse_installed.stat.isdir | default(False) == False) and eclipse_downloaded.stat.exists == False

- name:      Unarchive Eclipse tarball
  unarchive: src=/tmp/eclipse.tar.gz dest=/tmp copy=no
  when: (eclipse_installed.stat.isdir | default(False) == False) and eclipse_downloaded.stat.exists == False

- name:   Copy Eclipse to its final location
  shell:  cp -rp /tmp/eclipse /opt/eclipse
  when:   eclipse_installed.stat.isdir | default(False) == False
  become: yes

- name: Check if Eclipse already have PHP support
  find: path=/opt/eclipse/plugins patterns=org.eclipse.php.*
  register: eclipse_php

- name:  Install PHP support in Eclipse
  shell: DISPLAY=:1 /opt/eclipse/eclipse -clean -purgeHistory -nosplash -consolelog -debug -application org.eclipse.equinox.p2.director \
          -repository http://download.eclipse.org/releases/neon -installIU org.eclipse.php.feature.group
  when:  eclipse_php.matched == 0

# Eclim installation

- name: Check if Eclim has already been installed in a previous provisioning
  stat: path=/opt/eclipse/eclimd
  register: eclim_installed

- name: Check if Eclim has already been downloaded in a previous provisioning
  stat: path='/tmp/eclim-installer.jar'
  when: eclim_installed.stat.exists == False
  register: eclim_downloaded

- name: Download Eclim installer
  get_url:
    url:  https://github.com/ervandew/eclim/releases/download/2.6.0/eclim_2.6.0.jar
    dest: /tmp/eclim-installer.jar
  when: eclim_installed.stat.exists == False and eclim_downloaded.stat.exists == False

- name:  Install Eclim # Remember to install Eclim AFTER PHP support (and/or other plugins) are installed
  shell: java -Dvim.files={{ ansible_env.HOME }}/.vim -Declipse.home=/opt/eclipse -jar /tmp/eclim-installer.jar install
  when:  eclim_installed.stat.exists == False
  # NOTE: Never use the tilde character for vim.files: It will not be replace by your home, but will create a '~' directory!

- name: Configure Eclim workspace
  lineinfile:
    dest:        "{{ ansible_env.HOME }}/.eclimrc"
    line:        osgi.instance.area.default=@user.home/www
    create:      yes
    insertafter: EOF

- name: Configure Eclim default encoding
  lineinfile:
    dest:        "{{ ansible_env.HOME }}/.eclimrc"
    line:        file.encoding=utf-8
    create:      yes
    insertafter: EOF

# Virtual display
  # Command: (must be run each time the machine start, so need to make it auto-start)
  # Xvfb :1 -screen 0 1024x768x24 +extension RANDR &
# Eclim deamon
  # Command: (must be run by same user than one's runing eclim)
  # DISPLAY=:1 /opt/eclipse/eclimd -b -Xmx256M
  #
  # NOTE: After a few seconds, you will see errors displayed on screen, the official doc says to ignore them
  # (I don't like that...), this is true: I was abled to run Eclim and play with it despite of them

# To test all is OK, launch vi and exec ":PingEclim" for example.
# If the daemon is detected, you can exec ":ProjectCreate <path-in-eclipse-workspace-to-a-new-project-dir> -n php"
# If you receive an error "unknow php alias", then Eclipse PHP support is broken
# Otherwise, try editing a PHP file and type <CTRL-X><CTRL-U> to autocomplete

