#!/bin/sh
### BEGIN INIT INFO
# Provides:          xvfb
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Xvfb daemon
# Description:       Manage Xvfb status (start / stop / restart / status)
### END INIT INFO

NAME="xvfb"
PATH=/sbin:/bin:/usr/sbin:/usr/bin

XVFBBIN=/usr/bin/Xvfb
XVFBPID="/var/run/${NAME}.pid"
XVFBARG=":1 -screen 0 1024x768x24 +extension RANDR"

. /lib/lsb/init-functions

case "$1" in
  start)
    printf "Starting Xvfb... "
    start-stop-daemon --start --quiet --pidfile $XVFBPID --make-pidfile --background --exec $XVFBBIN -- $XVFBARG
    sleep 3
    printf "\n"
    ;;

  stop)
    printf "Stopping Xvfb... "
    start-stop-daemon --stop --quiet --pidfile $XVFBPID
    printf "\n"
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  status)
    status_of_proc -p $XVFBPID "$NAME" "$NAME" && exit 0 || exit $?
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0

